// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYiBw-y0IW9WDlYhTuUY9XgH6lmu3gLo',
    appId: '1:367308357028:web:f43c0d18cd2427fcf55531',
    messagingSenderId: '367308357028',
    projectId: 'benta-lacos',
    authDomain: 'benta-lacos.firebaseapp.com',
    storageBucket: 'benta-lacos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1weYFDxlHfMV04SsQvVKwlYXs9WSNdTA',
    appId: '1:367308357028:android:f229effdbde52c73f55531',
    messagingSenderId: '367308357028',
    projectId: 'benta-lacos',
    storageBucket: 'benta-lacos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyesised82xMgdcweqBHpLioCBTHJMP1o',
    appId: '1:367308357028:ios:8e0077c5a27f7bcbf55531',
    messagingSenderId: '367308357028',
    projectId: 'benta-lacos',
    storageBucket: 'benta-lacos.firebasestorage.app',
    iosBundleId: 'com.example.bentaLacos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyesised82xMgdcweqBHpLioCBTHJMP1o',
    appId: '1:367308357028:ios:8e0077c5a27f7bcbf55531',
    messagingSenderId: '367308357028',
    projectId: 'benta-lacos',
    storageBucket: 'benta-lacos.firebasestorage.app',
    iosBundleId: 'com.example.bentaLacos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYiBw-y0IW9WDlYhTuUY9XgH6lmu3gLo',
    appId: '1:367308357028:web:e081ef2690dcc372f55531',
    messagingSenderId: '367308357028',
    projectId: 'benta-lacos',
    authDomain: 'benta-lacos.firebaseapp.com',
    storageBucket: 'benta-lacos.firebasestorage.app',
  );
}
